import UserActivity from "../../models/Interactive_Visual_Task_Scheduler_Model/userActivityModel.js";
import cloudinary from "../../config/cloudinary.js";

// helper: upload buffer to Cloudinary using upload_stream
const uploadBufferToCloudinary = (buffer, folder) => {
  return new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      { folder },
      (error, result) => {
        if (error) return reject(error);
        resolve(result);
      }
    );
    stream.end(buffer); // send the in-memory file buffer
  });
};

// Controller to create a new routine
export const createUserActivity = async (req, res) => {
  try {
    const {
      created_by,
      title,
      description,
      age_group,
      development_area,
      steps,
      scheduled_date,
      estimated_duration_minutes,
      difficulty_level,
    } = req.body;

    // ------------ parse steps (comes as string in multipart) -------------
    let parsedSteps = [];
    if (typeof steps === "string") {
      // expecting JSON string from Postman/Flutter
      try {
        parsedSteps = JSON.parse(steps);
      } catch (e) {
        return res.status(400).json({ error: "steps must be valid JSON" });
      }
    } else if (Array.isArray(steps)) {
      parsedSteps = steps;
    }

    // Basic validations
    if (!created_by || !title || !description) {
      return res.status(400).json({
        error: "created_by, title, and description are required",
      });
    }

    if (!age_group) {
      return res.status(400).json({ error: "age_group is required" });
    }

    if (!development_area) {
      return res.status(400).json({ error: "development_area is required" });
    }

    if (!parsedSteps || !Array.isArray(parsedSteps) || parsedSteps.length === 0) {
      return res.status(400).json({
        error: "Activity must contain at least one step",
      });
    }

    if (!scheduled_date) {
      return res.status(400).json({ error: "scheduled_date is required" });
    }

    if (!estimated_duration_minutes) {
      return res
        .status(400)
        .json({ error: "estimated_duration_minutes is required" });
    }

    if (!difficulty_level) {
      return res.status(400).json({ error: "difficulty_level is required" });
    }

    // ---------------- CLOUDINARY UPLOAD (multer + buffer) ----------------
    let mediaLinksArray = [];

    if (req.file) {
      try {
        const result = await uploadBufferToCloudinary(
          req.file.buffer,
          "chromabloom/user_activities"
        );
        mediaLinksArray.push(result.secure_url); // 👈 store URL
      } catch (error) {
        console.error("Cloudinary Upload Error:", error);
        return res.status(500).json({
          error: "Image upload failed",
          details: error.message,
        });
      }
    }

    // Create activity (user_activityId is auto-generated by pre('save'))
    const activity = await UserActivity.create({
      created_by,
      title,
      description,
      age_group,
      development_area,
      steps: parsedSteps,
      scheduled_date,
      estimated_duration_minutes,
      difficulty_level,
      media_links: mediaLinksArray.length > 0 ? mediaLinksArray : [],
    });

    return res.status(201).json({
      message: "User activity created successfully",
      data: activity,
    });
  } catch (error) {
    return res.status(500).json({
      message: "Internal server error",
      error: error.message,
    });
  }
};

// GET all activities in the system
export const getAllActivities = async (req, res) => {
  try {
    const activities = await UserActivity.find().sort({ scheduled_date: 1 });

    return res.status(200).json({
      message: "All activities fetched successfully",
      data: activities,
    });

  } catch (error) {
    return res.status(500).json({
      message: "Internal server error",
      error: error.message,
    });
  }
};

// GET all activities created by one caregiver
export const getAllUserActivities = async (req, res) => {
  try {
    const { caregiverId } = req.params;

    if (!caregiverId) {
      return res.status(400).json({
        error: "caregiverId is required",
      });
    }

    const activities = await UserActivity.find({
      created_by: caregiverId,
    }).sort({ scheduled_date: 1 }); // Sorting by upcoming schedule

    return res.status(200).json({
      message: "All caregiver activities fetched successfully",
      data: activities,
    });

  } catch (error) {
    return res.status(500).json({
      message: "Internal server error",
      error: error.message,
    });
  }
};

// Get User Activities by Caregiver ID and Date
export const getUserActivitiesByDate = async (req, res) => {
  try {
    const { caregiverId, date } = req.body;

    if (!caregiverId || !date) {
      return res.status(400).json({
        error: "caregiverId and date are required",
      });
    }

    // Convert date string to Date object
    const selectedDate = new Date(date);
    if (isNaN(selectedDate.getTime())) {
      return res.status(400).json({ error: "Invalid date format" });
    }

    // Start of day
    const start = new Date(selectedDate);
    start.setHours(0, 0, 0, 0);

    // End of day
    const end = new Date(selectedDate);
    end.setHours(23, 59, 59, 999);

    const activities = await UserActivity.find({
      created_by: caregiverId,
      scheduled_date: { $gte: start, $lte: end },
    }).sort({ scheduled_date: 1 });

    return res.status(200).json({
      message: "Activities fetched successfully",
      data: activities,
    });

  } catch (error) {
    return res.status(500).json({
      message: "Internal server error",
      error: error.message,
    });
  }
};

// Delete User Activity by ID
export const deleteUserActivity = async (req, res) => {
  try {
    const { activityId } = req.params;

    if (!activityId) {
      return res.status(400).json({ error: "Activity ID is required" });
    }

    const deletedActivity = await UserActivity.findByIdAndDelete(activityId);

    if (!deletedActivity) {
      return res.status(404).json({ error: "User activity not found" });
    }

    return res.status(200).json({
      message: "User activity deleted successfully",
      data: deletedActivity,
    });

  } catch (error) {
    return res.status(500).json({
      message: "Internal server error",
      error: error.message,
    });
  }
};

// Update User Activity by ID
export const updateUserActivity = async (req, res) => {
  try {
    const { activityId } = req.params;

    if (!activityId) {
      return res.status(400).json({ error: "Activity ID is required" });
    }

    const {
      created_by,
      title,
      description,
      age_group,
      development_area,
      steps,
      scheduled_date,
      estimated_duration_minutes,
      difficulty_level,
      media_image_base64, // optional new image
    } = req.body;

    // Find existing activity
    const existingActivity = await UserActivity.findById(activityId);

    if (!existingActivity) {
      return res.status(404).json({ error: "User activity not found" });
    }

    // OPTIONAL: Upload new image if provided
    let uploadedImageUrl = existingActivity.media_links?.[0] || null;

    if (media_image_base64) {
      try {
        const uploadResult = await cloudinary.uploader.upload(
          media_image_base64,
          {
            folder: "chromabloom/user_activities",
          }
        );
        uploadedImageUrl = uploadResult.secure_url;
      } catch (imgErr) {
        console.error("Cloudinary upload error:", imgErr);
        return res.status(500).json({ error: "Image upload failed" });
      }
    }

    // Build update object
    const updatedData = {
      created_by: created_by ?? existingActivity.created_by,
      title: title ?? existingActivity.title,
      description: description ?? existingActivity.description,
      age_group: age_group ?? existingActivity.age_group,
      development_area: development_area ?? existingActivity.development_area,
      steps: steps ?? existingActivity.steps,
      scheduled_date: scheduled_date ?? existingActivity.scheduled_date,
      estimated_duration_minutes:
        estimated_duration_minutes ?? existingActivity.estimated_duration_minutes,
      difficulty_level: difficulty_level ?? existingActivity.difficulty_level,
      media_links: uploadedImageUrl ? [uploadedImageUrl] : existingActivity.media_links,
    };

    // Perform update
    const updatedActivity = await UserActivity.findByIdAndUpdate(
      activityId,
      updatedData,
      {
        new: true,
        runValidators: true,
      }
    );

    return res.status(200).json({
      message: "User activity updated successfully",
      data: updatedActivity,
    });
  } catch (error) {
    return res.status(500).json({
      message: "Internal server error",
      error: error.message,
    });
  }
};
